#!/usr/bin/env bash
#
# SessionStart hook for Claude Code on the web.
#
# The web base image ships older/leaner tooling than this project assumes. This
# hook brings it in line — the web-runtime analogue of .devcontainer/post-create.sh.
# It does three things: point the shell at the project's Python, sync the venv,
# and install the agent-friendly CLI tools the dev container ships as features.
#
# The venv sync runs asynchronously (see the {"async": true} line below): the
# session starts immediately while setup proceeds in the background. The PATH
# export is written *before* that handoff so it always lands for this session.
# Safe to run repeatedly; the container state is cached after it completes, so
# subsequent sessions skip the slow paths.
#
# A web session that clones more than one repository puts them side by side under
# a working directory with no .claude/settings.json of its own, so this hook is never
# registered there: CLAUDE_PROJECT_DIR is unset, and none of the below happens. The
# tell is `./go` refusing with "uv ... is too old" (the image's uv then also picks a
# pre-release Python for the venv). The remedy is to run it by hand from the repo:
#
#     CLAUDE_CODE_REMOTE=true CLAUDE_PROJECT_DIR=$PWD .claude/hooks/session-start.sh
#
set -euo pipefail

# Web-only. Local checkouts and the dev container manage their own tooling
# (the devcontainer installs uv via a feature), so don't interfere there.
if [[ "${CLAUDE_CODE_REMOTE:-}" != 'true' ]]; then
    exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-.}"
project_dir="$PWD"

log() { echo "session-start: $*" >&2; }

# 1. Ensure uv is new enough to parse pyproject.toml — first, ahead of both the
#    orientation probe and the async handoff. The image ships uv 0.8.x, which
#    can't parse the relative `exclude-newer = "N days"` cooldown: it drops the
#    cutoff (and the rest of `[tool.uv]`, so a `required-version` guard there
#    can't catch it), re-resolves to newer packages, downloads them, and
#    rewrites uv.lock. Any `./go` or `uv run` in the window before the upgrade
#    lands did just that, so the upgrade has to finish first. It takes under a
#    second even on a cold cache, which is why it fits ahead of the map.
#    We upgrade from PyPI rather than via `uv self update`, because that checks
#    GitHub releases and the network policy here blocks the GitHub API (403).
min_uv='0.11'
have_uv="$(uv --version 2>/dev/null | awk '{print $2}' || echo '0')"
if [[ "$(printf '%s\n%s\n' "$min_uv" "$have_uv" | sort -V | head -n1)" != "$min_uv" ]]; then
    log "upgrading uv ${have_uv} -> latest (from PyPI)"
    uv tool install uv --force >/dev/null 2>&1 || log "uv upgrade failed; continuing with ${have_uv}"
fi

# 2. Print a compact orientation MAP synchronously, before the async handoff
#    below — stdout printed after that handoff isn't reliably delivered as
#    context. It's a map, not a manual: injected tokens are re-counted every
#    turn for the rest of the session, so this points at where to look rather
#    than dumping file contents you can read on demand. It surfaces only what
#    recent sessions actually reached for during orientation (git state, which
#    resources are wired up, which experiments exist, and where the infra/why
#    and backlog live) — everything here is cheap: git, env-var presence, and
#    one `git ls-files`, no venv/network/deps (all of which are still syncing).
(
    set +e
    echo "## Orientation (auto-generated by .claude/hooks/session-start.sh — a map, see AGENTS.md)"
    echo
    echo "Git — $(git branch --show-current), $(git status --short | wc -l | tr -d ' ') uncommitted:"
    git log --oneline -3 | sed 's/^/  /'
    echo
    # Resource wiring from env-var presence — no network/deps. `./go auth --check`
    # verifies the tokens live, and says which storage pairs the token can write;
    # this just says what's plausibly wired up.
    on() { [[ -n "${!1:-}" ]] && printf on || printf OFF; }
    echo "Resources (env presence; ./go auth --check for live status):" \
         "Modal $(on MODAL_TOKEN_ID) · HF $(on HF_TOKEN)"
    # Which storage pair this environment writes to. A web environment has no
    # mini.local.toml, so it names the pair by variable rather than by profile
    # (mi-ni skill, storage reference); the names aren't secret, so print them.
    storage="Storage: ${MINI_STORE_BUCKET:-<pyproject default>} · publish ${MINI_PUBLISH_REPO:-<pyproject default>}"
    echo "${storage}${MINI_PROFILE:+ · profile $MINI_PROFILE}"
    echo
    echo "Experiments (report.py dirs; annotated status in docs/index.md):"
    git ls-files 'docs/**/report.py' | sed 's#/report.py##; s#^docs/#  #' | paste -sd' '
    echo "This is not an environment the human has direct access to, so if you are working on an experiment, send them relevant files to review (e.g. figures and reports)."
    echo "The human reviews drafts on a reMarkable. After './go render <report> -o .mini/prints/<name>.pdf', send them the PDF the same way (name it for the report, e.g. ex-2.2.15.pdf, so it needs no renaming on the tablet). From the second round on, add '--since <commit>' (see /pdf-annotations) so the PDF shows what changed."
    echo "When opening a PR, subscribe to its activity if you can, and then stop: don't poll it or schedule check-ins to re-read its state. Subscriptions cover CI failures and review comments, and the human will say when something a subscription wouldn't notice (a merge, a base-branch change) needs attention."
    echo
    # The two CLIs, generated rather than pinned here so they can't drift. Both
    # are cheap enough for the synchronous path: `./go` prints its usage in pure
    # bash, and mini is called as the venv binary rather than through `uv run`,
    # so nothing here can trigger the sync that step 5 below defers. `./go` does
    # read `uv --version` for its guard, though, and on a cold container it
    # reported that guard failing as the whole tooling line — which is why the
    # upgrade in step 1 runs above this block rather than below it. The venv
    # doesn't exist yet on a cold container, hence the guard — the first session
    # gets one line, every later one gets both.
    echo "Project tooling: $(./go 2>&1)"
    if [[ -x .venv/bin/mini ]]; then
        echo "Experiments: $(COLUMNS=200 MINI_PROG=bin/mini .venv/bin/mini 2>&1)"
    fi
) 2>/dev/null || true

# 3. Put the project venv first on PATH so bare `python` resolves to the
#    project's 3.14 interpreter instead of the image's system Python 3.11 (which
#    chokes on 3.14-only syntax), and so `ruff`, `ty`, `pytest`,
#    `mini`, and `modal` are callable without the `uv run`/`./go` prefix.
#    CLAUDE_ENV_FILE is sourced into the session's shells by Claude Code; we
#    write it synchronously, before the async handoff below, so it applies even
#    though the heavy setup is still running. $PATH stays unexpanded (single
#    quotes via escaping) so it composes with each shell's PATH; the guard keeps
#    repeated SessionStart events (resume/clear/compact) from stacking entries.
if [[ -n "${CLAUDE_ENV_FILE:-}" ]]; then
    if ! grep -qs "$project_dir/.venv/bin" "$CLAUDE_ENV_FILE"; then
        echo "export PATH=\"$project_dir/.venv/bin:\$PATH\"" >> "$CLAUDE_ENV_FILE"
        log "added .venv/bin to PATH"
    fi
fi

# 3b. Share the render caches between the project's threads. Each thread runs in
#    its own container, and /mnt/project-files is the one folder they all mount,
#    so MINI_CACHE_DIR points mini's shareable caches there: the weave cache
#    (lit-cache: memoized figures and computations, with copies of the figure
#    files) and the bucket's warm cache (store-cache: content-addressed blobs).
#    Both write through a temp file and a rename, so concurrent writers are
#    safe, and a report rendered in one thread takes about two seconds in every
#    other. Elsewhere (a laptop, the dev container) the folder doesn't exist and
#    the caches stay under .mini/. An environment that sets MINI_CACHE_DIR
#    itself keeps its own value.
if [[ -n "${CLAUDE_ENV_FILE:-}" && -d /mnt/project-files && -z "${MINI_CACHE_DIR:-}" ]]; then
    if ! grep -qs "MINI_CACHE_DIR" "$CLAUDE_ENV_FILE"; then
        echo "export MINI_CACHE_DIR=/mnt/project-files/.mini-cache" >> "$CLAUDE_ENV_FILE"
        log "shared the render caches via MINI_CACHE_DIR"
    fi
fi

# 4. Skip mechanical-reformat commits in `git blame` (see .git-blame-ignore-revs).
#    The dev container sets this in post-create.sh and `./go install` sets it for
#    local checkouts; the web image runs neither, and the config is repo-local so
#    it can't be committed. Fast and local, so it runs synchronously here rather
#    than in the async block below.
if [[ -d .git ]]; then
    git config --local blame.ignoreRevsFile .git-blame-ignore-revs \
        && log 'configured blame.ignoreRevsFile' || true
fi

# Everything below is slow; run it in the background so the session starts now.
# `uv run` syncs on demand anyway, so the worst case is the first command
# re-doing work this hook is also doing.
echo '{"async": true, "asyncTimeout": 600000}'

# 5. Sync the project venv so linters, type-checker, tests, and reports work.
#    Mirrors `./go install` (minus npm/git-hooks, which the agent doesn't need).
#    --no-group cuda: locally we run CPU-only; the CUDA plugin is for Modal.
log "syncing venv (uv $(uv --version 2>/dev/null | awk '{print $2}'))"
uv sync --all-groups --no-group cuda --locked >/dev/null 2>&1 || log 'uv sync failed (stale uv.lock? run `uv lock`); venv may be incomplete'

# 6. Install the agent-friendly CLI tools the dev container ships as features
#    but the web image lacks: fd, fzf, bat. (rg is already present; gh is
#    omitted because this network policy blocks the GitHub API — use the GitHub
#    MCP tools instead.) Debian packages the binaries as fdfind/batcat to avoid
#    name clashes, so symlink the names CLAUDE.md actually uses. The whole hook
#    is web-only (guarded above), but gate on apt-get too so this degrades
#    cleanly should the cloud base image ever not be Debian-based.
if command -v apt-get >/dev/null 2>&1 \
    && ! { command -v fd && command -v bat && command -v fzf; } >/dev/null 2>&1; then
    log 'installing fd, fzf, bat'
    if DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        fd-find fzf bat >/dev/null 2>&1; then
        [[ -e /usr/bin/fdfind ]] && ln -sf /usr/bin/fdfind /usr/local/bin/fd
        [[ -e /usr/bin/batcat ]] && ln -sf /usr/bin/batcat /usr/local/bin/bat
    else
        log 'apt install of fd/fzf/bat failed; continuing'
    fi
fi

log 'ready'
exit 0
