import marimo

__generated_with = "0.23.9"
app = marimo.App(
    width="medium",
    app_title="Ex 2.1.3: names all the way down",
    css_file="../../report.css",
    auto_download=["html"],
)

with app.setup(hide_code=True):
    import json
    import tempfile
    from pathlib import Path

    import marimo as mo  # noqa: F401
    import matplotlib.pyplot as plt
    import numpy as np

    # Marimo puts the notebook's directory on sys.path, so the experiment
    # definition is importable — refs and sweep constants can't drift.
    from experiment import (
        ARRAYS_REF,
        EVALS_REF,
        HOLDOUT_FRAC,
        METRICS_REF,
        N_EXAMPLES,
        SEEDS,
    )
    from mini.reports import report_bundle, use_publisher
    from mini.store import project_store
    from mini.vis import figure_html, light_dark, themed
    from sca.data import named_colors as nc
    from sca.data.colors import N_LEVELS, load_example_sets, to_hex

    use_publisher(report_bundle(__file__))

    GRID_NAMES = list(nc.GRIDS)
    PALETTES = {g: nc.grid_palette(nc.GRIDS[g]) for g in GRID_NAMES}
    VOCAB_RGB = {g: np.array(list(p.values()), dtype=np.float32) / (N_LEVELS - 1) for g, p in PALETTES.items()}

    def load_results() -> tuple[dict, dict[str, np.ndarray], dict[str, dict]] | None:
        """Resolve metrics, arrays, and eval sets from the store, or None if unpublished."""
        store = project_store()
        m_art, a_art = store.get_ref(METRICS_REF), store.get_ref(ARRAYS_REF)
        e_arts = {g: store.get_ref(f"{EVALS_REF}/{g}") for g in GRID_NAMES}
        if m_art is None or a_art is None or any(v is None for v in e_arts.values()):
            return None
        with tempfile.TemporaryDirectory() as d:
            metrics = json.loads(store.get(m_art, Path(d) / "metrics.json").read_text())
            with np.load(store.get(a_art, Path(d) / "arrays.npz")) as z:
                arrays = {k: z[k] for k in z.files}
            evals = {
                g: load_example_sets(store.get(art, Path(d) / f"{g}.json").read_bytes())
                for g, art in e_arts.items()
                if art is not None
            }
        return metrics, arrays, evals

    def cell_of(metrics: dict, grid: str, s: int) -> dict:
        (r,) = [r for r in metrics["cells"] if r["label"] == f"{grid}-s{s}"]
        return r

    def grid_shades() -> dict[str, tuple]:
        stops = light_dark([0.82, 0.55, 0.32, 0.08], [0.88, 0.62, 0.42, 0.2])
        return dict(zip(GRID_NAMES, plt.cm.viridis(stops), strict=True))

    def sw(name: str, grid: str) -> str:
        """Inline swatch + name for any grid's palette (the classic `swatch` knows only the 27)."""
        rgb = PALETTES[grid].get(name)
        if rgb is None:
            return f"<code>{name}</code>"
        return f'<span class="sw" style="--sw: {to_hex(rgb)};" aria-hidden="true"></span> {name}'

    def dists_for(grid: str, exs: list, logp: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """(guess distance, floor distance) per example, unit-cube units."""
        result = np.array([ex.result for ex in exs], dtype=np.float32) / (N_LEVELS - 1)
        d = np.linalg.norm(VOCAB_RGB[grid][None] - result[:, None], axis=2)
        return d[np.arange(len(exs)), logp.argmax(axis=1)], d.min(axis=1)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    # Ex 2.1.3: names all the way down

    Every experiment so far has taught the model colors two ways at once: as
    names (`red`) and as hex codes (`#f00`), tied together by alias lines. The
    hex form is a gift. It spells the value out one channel at a time, so the
    geometry of color space is legible right there in the text. And
    [ex-2.1.2](../ex-2.1.2/) found that the models lean on that gift hard:
    name + name arithmetic works when the answer may be *written* in hex, and
    the piece that never trains is exactly the translation back from a value
    to a name.

    So here is the natural control: take the hex away entirely. In this
    experiment's language, a color is a single opaque token, and the only
    sentences are mixing equations between named colors whose mix is itself
    named. No aliases, no digits, no characters. Nothing in the token stream
    says that colors live on a 3D grid, that `purple` sits midway between
    `red` and `blue`, or that colors are *values* at all. The only structure
    left is the co-occurrence statistics of the mixing table.

    The question, from the [science todo](https://github.com/z0u/sca2/blob/main/todo-science.md):
    can the model infer the color-space geometry from that alone? This is
    matrix completion wearing a language-model costume. The mixing table is a
    large symmetric table whose entries are generated by a tiny latent rule
    (each color is a point in a 3D cube; mixing is the channel-wise mean). A
    model that discovers the rule can fill in cells of the table it has never
    seen; a model that memorizes the table cell by cell cannot. Held-out pairs
    separate the two.

    There's a second, softer question. Many operand pairs mix to a color that
    has no name in the vocabulary at all, so exact answers are impossible
    there. But a model that has the geometry should still guess a *nearby*
    name. Measuring how close the guesses land gives a graded score that
    exact-match accuracy can't, and it is the score that matters for the
    anchored experiments to come: an anchor doesn't need the model to be
    right, it needs the model's representation to be geometrically organized.
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(rf"""
    ## The language, and a vocabulary-size sweep

    A vocabulary is a level sub-grid of the 16-level RGB cube: pick a set of
    levels, name every point of levels³. We sweep four grids. The 3-level grid
    is the classic 27-color palette from the base language, names and all. The
    denser grids use synthetic names that encode the value (`c05f` is the
    color `#05f`) — purely for our benefit when reading failures; each name is
    a single token, so the model sees an opaque id and has to learn what it
    means from usage, exactly as it would for `red`.

    | grid | levels per channel | colors | example |
    |------|--------------------|-------:|---------|
    | `v27` | 0, 8, 15 | 27 | `red`, `purple` |
    | `v64` | 0, 5, 10, 15 | 64 | `c05f` |
    | `v216` | 0, 3, 6, 9, 12, 15 | 216 | `c9c3` |
    | `v4096` | all 16 | 4096 | `c27b` |

    Every training line is `a + b = mix(a, b)`, six tokens including the
    newline, where both operands and the mix are vocabulary colors. Mixing is
    the same channel-wise round-half-up mean as always. A pair whose mix lands
    on the vocabulary is *closed*; {HOLDOUT_FRAC:.0%} of the distinct closed
    pairs are held out of training entirely. Pairs whose mix falls off the
    vocabulary are *open*: they never appear in training (there is no way to
    write their answer), and we use them purely as probes of graded
    generalization. The corpus is {N_EXAMPLES:,} lines drawn i.i.d. from the
    train-side closed pairs; the backbone is the frozen d64-L4 nGPT cell from
    ex-2.1.1, {len(SEEDS)} seeds per grid.

    A few lines from two of the corpora:
    """)
    return


@app.cell(hide_code=True)
def _():
    _v27 = "".join(ex.text for ex in nc.sample_corpus(5, 0, nc.GRIDS["v27"]))
    _v216 = "".join(ex.text for ex in nc.sample_corpus(5, 0, nc.GRIDS["v216"]))
    mo.hstack(
        [mo.md(f"`v27`:\n```\n{_v27}```"), mo.md(f"`v216`:\n```\n{_v216}```")],
        justify="start",
        gap=3,
    )
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    The sweep changes two things at once, and that is deliberate. A denser
    grid means more colors to name (a harder vocabulary) but also many more
    closed pairs constraining each color (richer co-occurrence evidence). At
    the extreme, the full 16-level grid has 4096 colors and 8.4 million
    distinct closed pairs, of which a 100k-line corpus can visit about 1% —
    there, memorization stops being an option and the model either finds the
    rule or fails. The small grids are the opposite: 49 distinct closed pairs
    at `v27`, so the table is trivially memorizable and the held-out fifth of
    it asks for inference from very little evidence.

    ## What we measure

    Answers are single tokens, so one forward pass per prompt gives the whole
    picture. From the next-token distribution at the `=` position we take:
    exact-match accuracy and the cross-entropy of the true answer (on closed
    pairs, where a true answer exists); the RGB distance from the model's
    highest-probability color to the true mix (any pair — this is the graded
    score); and two reference distances per prompt, the *floor* (distance from
    the true mix to the nearest vocabulary color at all: zero for closed
    pairs) and *chance* (the mean distance over the whole vocabulary, i.e.
    what an ignorant guesser scores in expectation).

    Then two geometry probes. A ridge probe from the color-token embeddings to
    RGB asks whether the embedding table itself became a color cube. And
    per-layer probes from the residual stream at the pre-answer position to
    the mix's RGB ask whether the answer is computed *in value space* on the
    way to being emitted, as it is in the hex-trained models.

    ## Hypotheses

    Stated before looking at any results.

    **H1.** Seen pairs are answered near-perfectly on every grid; the corpus
    gives each seen pair many effective repetitions even at `v4096`.

    **H2.** Held-out accuracy rises with grid size. `v27` stays near zero
    (39 training pairs constrain 27 colors too weakly, echoing the base
    language's unsolved `named_holdout`, though for reasons of evidence
    rather than translation); `v4096`, if it learns the seen pairs at all,
    must be generalizing, so its held-out accuracy should approach its seen
    accuracy. The interesting territory is the middle.

    **H3.** Where held-out accuracy is high, guessed colors on open pairs land
    near the floor distance, well below chance; where it is low, guesses sit
    at or near chance.

    **H4.** Embedding geometry tracks behavior: the embedding → RGB probe's R²
    and the low-dimensionality of the embedding table (top-3 explained
    variance) rise with grid size, and a PCA of the embeddings shows the color
    cube where, and only where, held-out performance is good.

    **H5.** Uncertain, stated as a watch item: at `v4096` the fixed 100-epoch
    budget may not be enough for the rule to crystallize (grokking-style late
    generalization is a known failure mode of small algorithmic tasks), in
    which case seen accuracy will be middling too and the run says
    "undertrained", not "impossible".
    """)
    return


@app.cell(hide_code=True)
def _():
    loaded = load_results()
    return (loaded,)


@app.cell(hide_code=True)
def _(loaded):
    mo.stop(
        loaded is None,
        mo.md(
            "No results yet — run the experiment (it publishes metrics, arrays, eval sets, "
            "and checkpoints on completion):\n\n"
            "```bash\nbin/mini run docs/m2/ex-2.1.3/experiment.py --app modal --max-containers 9\n```"
        ),
    )
    metrics, arrays, evals = loaded
    return arrays, evals, metrics


@app.cell(hide_code=True)
def _(metrics):
    _stats = metrics["corpus_stats"]
    _rows = "".join(
        f"<tr><td><code>{g}</code></td>"
        f'<td class="num">{s["n_colors"]:,}</td>'
        f'<td class="num">{s["n_closed_distinct"]:,}</td>'
        f'<td class="num">{s["n_seen_distinct"]:,}</td>'
        f'<td class="num">{s["n_holdout"]:,}</td>'
        f'<td class="num">{s["n_open"]:,}</td>'
        "</tr>"
        for g, s in _stats.items()
    )
    _table = (
        '<div class="report-table-scroll"><table class="report-table">'
        '<tr><th>grid</th><th class="num">colors</th><th class="num">closed pairs</th>'
        '<th class="num">distinct pairs in corpus</th><th class="num">held out</th>'
        '<th class="num">open pairs</th></tr>' + _rows + "</table></div>"
    )
    _caption = mo.md(
        """
        Pair accounting per grid. "Closed pairs" counts distinct unordered pairs whose
        mix is on-vocabulary (self-pairs excluded); the corpus draws (with repetition)
        from the non-held-out side. At `v4096` the corpus visits ~1% of the closed
        pairs, and every pair is closed, so there are no open pairs to probe.
        """
    ).text
    mo.Html(figure_html(_table, caption=_caption, class_="report-figure"))
    return


@app.cell(hide_code=True)
def _(metrics):
    @themed(
        name="val-loss",
        alt_text="""
            Validation loss against training epoch, one line per vocabulary grid (v27,
            v64, v216, v4096), three seeds each drawn as thin overlapping lines. Larger
            vocabularies start at higher loss (larger vocabulary means higher chance
            cross-entropy).
        """,
        caption="""
            Validation loss per epoch (three thin lines per grid: the seeds). The
            grids are not directly comparable — chance loss grows with the
            vocabulary — but each curve's own convergence is what matters here.
        """,
    )
    def _plot() -> plt.Figure:
        fig, ax = plt.subplots(figsize=(7.0, 3.6))
        shades = grid_shades()
        for g in GRID_NAMES:
            for s in SEEDS:
                vl = cell_of(metrics, g, s)["val_loss"]
                ax.plot(vl, color=shades[g], lw=1.0, alpha=0.8, label=g if s == 0 else None)
        ax.set(xlabel="epoch", ylabel="validation loss")
        ax.legend()
        ax.grid(alpha=0.3)
        return fig

    mo.Html(_plot())
    return


@app.cell(hide_code=True)
def _(metrics):
    _sets = ["named_seen", "named_holdout"]

    @themed(
        name="accuracy",
        alt_text="""
            Two bar panels of exact-match accuracy (0 to 1) against vocabulary grid
            (v27, v64, v216, v4096): seen pairs and held-out pairs. Bars show the mean
            over three seeds, dots the individual seeds.
        """,
        caption="""
            Exact-match accuracy by grid: the bar is the mean over three seeds, the
            dots are individual seeds. Seen pairs measure whether training worked at
            all; held-out pairs measure generalization — they can only be answered by
            inferring the latent geometry, because their equations never appear in
            training.
        """,
    )
    def _plot() -> plt.Figure:
        fig, axes = plt.subplots(1, len(_sets), figsize=(8.4, 3.2), sharey=True)
        shades = grid_shades()
        xs = np.arange(len(GRID_NAMES))
        for ax, es in zip(axes, _sets, strict=True):
            per_seed = np.array([[cell_of(metrics, g, s)["sets"][es]["accuracy"] for s in SEEDS] for g in GRID_NAMES])
            ax.bar(xs, per_seed.mean(axis=1), color=[shades[g] for g in GRID_NAMES], width=0.62)
            for i in range(len(GRID_NAMES)):
                ax.plot([xs[i]] * len(SEEDS), per_seed[i], "o", color="#0008", ms=3, zorder=3)
            ax.set(title=es.replace("_", " "), ylim=(-0.03, 1.03))
            ax.set_xticks(xs, GRID_NAMES)
            ax.grid(alpha=0.3, axis="y")
        axes[0].set_ylabel("exact-match accuracy")
        return fig

    mo.Html(_plot())
    return


@app.cell(hide_code=True)
def _(evals, arrays, metrics):
    _panels = [("named_holdout", "held-out pairs"), ("open", "open pairs")]

    @themed(
        name="distance-ecdf",
        alt_text="""
            Two panels of cumulative distributions of the RGB distance from the model's
            guessed color to the true mix, pooled over three seeds: held-out pairs and
            open pairs. One line per vocabulary grid. Dashed line: the nearest-name
            floor on open pairs. Vertical ticks on the x-axis mark each grid's chance
            distance.
        """,
        caption="""
            How close do guesses land? Each line is the cumulative distribution of the
            guess → true-mix distance (unit-cube units, pooled over seeds); higher and
            further left is better. On held-out pairs an exact answer exists, so the
            value at distance 0 is the exact-match accuracy. On open pairs no name is
            exactly right; the dashed line is the distribution of the best achievable
            (nearest-name) distance there, and the tick under each axis marks a grid's
            chance distance — where guesses land if the model knows nothing about the
            operands.
        """,
    )
    def _plot() -> plt.Figure:
        fig, axes = plt.subplots(1, len(_panels), figsize=(8.4, 3.4), sharey=True)
        shades = grid_shades()
        for ax, (es, title) in zip(axes, _panels, strict=True):
            for g in GRID_NAMES:
                if es not in evals[g]:
                    continue
                exs = evals[g][es]
                gd = np.concatenate([dists_for(g, exs, arrays[f"{g}-s{s}/logp/{es}"])[0] for s in SEEDS])
                fl = dists_for(g, exs, arrays[f"{g}-s0/logp/{es}"])[1]
                xs = np.sort(gd)
                ax.plot(xs, np.arange(1, len(xs) + 1) / len(xs), color=shades[g], lw=1.6, label=g)
                if es == "open":
                    xf = np.sort(fl)
                    ax.plot(xf, np.arange(1, len(xf) + 1) / len(xf), color=shades[g], lw=1.0, ls="--", alpha=0.7)
                chance = np.mean([cell_of(metrics, g, s)["sets"][es]["chance_dist"] for s in SEEDS])
                ax.plot([chance], [-0.02], marker="|", ms=8, color=shades[g], clip_on=False)
            ax.set(title=title, xlabel="distance to true mix", xlim=(-0.02, 1.0), ylim=(-0.03, 1.03))
            ax.grid(alpha=0.3)
        axes[0].set_ylabel("fraction of prompts ≤ x")
        axes[0].legend(loc="lower right", fontsize=8)
        return fig

    mo.Html(_plot())
    return


@app.cell(hide_code=True)
def _(arrays, metrics):
    @themed(
        name="embedding-pca",
        alt_text="""
            Four scatter panels, one per vocabulary grid, showing the first two
            principal components of each grid's color-token embeddings; every point is
            colored with the actual color it names. A recovered geometry appears as a
            smooth, organized color gradient; a failed one as a jumble.
        """,
        caption="""
            The embedding table, projected onto its own first two principal components
            (seed 0), each token drawn in the color it names. No axis means anything by
            itself; what matters is whether nearby points have nearby colors. The
            annotation gives the ridge-probe R² from the full 64-d embedding to RGB
            (mean over seeds) — the quantitative version of "is this a color cube?".
        """,
    )
    def _plot() -> plt.Figure:
        fig, axes = plt.subplots(1, len(GRID_NAMES), figsize=(11.5, 3.1))
        for ax, g in zip(axes, GRID_NAMES, strict=True):
            emb = arrays[f"{g}-s0/embeddings"]
            centered = emb - emb.mean(0)
            _, _, vt = np.linalg.svd(centered, full_matrices=False)
            z = centered @ vt[:2].T
            z /= np.abs(z).max() + 1e-9
            n = len(emb)
            ax.scatter(z[:, 0], z[:, 1], c=VOCAB_RGB[g], s=max(3.0, 60_000 / (n * 4)), lw=0)
            r2 = np.mean([cell_of(metrics, g, s)["emb_r2"] for s in SEEDS])
            ax.set_title(f"{g}   (R² {r2:.2f})", fontsize=10)
            ax.set_aspect("equal")
            ax.set_xlim(-1.1, 1.1)
            ax.set_ylim(-1.1, 1.1)
            ax.set_axis_off()
        return fig

    mo.Html(_plot())
    return


@app.cell(hide_code=True)
def _(metrics):
    @themed(
        name="residual-probes",
        alt_text="""
            Four line panels, one per vocabulary grid, of ridge-probe R-squared for the
            mix's RGB read from the residual stream at the pre-answer position, against
            residual depth 0 to 4. Lines: seen pairs (probe fit set), held-out pairs,
            and open pairs.
        """,
        caption="""
            Is the answer computed in value space before it is emitted? Ridge probes
            from the pre-answer residual stream to the true mix's RGB, per depth
            (0 = embeddings, 4 = final), fit on half the seen prompts (seed 0). Transfer
            to held-out and open prompts distinguishes a genuine value-space
            computation from a probe that memorized the fit set.
        """,
    )
    def _plot() -> plt.Figure:
        fig, axes = plt.subplots(1, len(GRID_NAMES), figsize=(11.5, 3.0), sharey=True)
        styles = {"named_seen": "-", "named_holdout": "--", "open": ":"}
        shades = grid_shades()
        for ax, g in zip(axes, GRID_NAMES, strict=True):
            probe = cell_of(metrics, g, 0)["probe_r2"]
            for es, r2s in probe.items():
                ax.plot(r2s, styles.get(es, "-"), color=shades[g], label=es.replace("_", " "))
            ax.set(title=g, xlabel="depth", ylim=(-0.1, 1.03))
            ax.grid(alpha=0.3)
        axes[0].set_ylabel("probe R² (mix RGB)")
        axes[0].legend(fontsize=7, loc="upper left")
        return fig

    mo.Html(_plot())
    return


@app.cell(hide_code=True)
def _(evals, arrays):
    def completion_rows(grid: str, es: str, k: int = 6) -> str:
        exs = evals[grid][es]
        lp = arrays[f"{grid}-s0/logp/{es}"]
        names = list(PALETTES[grid])
        gd, fl = dists_for(grid, exs, lp)
        order = np.argsort(-gd)[:k]  # the widest misses are the most informative
        rows = []
        for i in order:
            ex = exs[i]
            a, b = ex.prompt.split()[0], ex.prompt.split()[2]
            true = (
                sw(ex.answer, grid)
                if ex.answer
                else f'<span class="sw" style="--sw: {to_hex(ex.result)};" aria-hidden="true"></span> <code>{to_hex(ex.result)}</code>'
            )
            rows.append(
                f"<tr><td>{sw(a, grid)}</td><td>{sw(b, grid)}</td><td>{true}</td>"
                f'<td>{sw(names[int(lp[i].argmax())], grid)}</td><td class="num">{gd[i]:.2f}</td>'
                f'<td class="num">{fl[i]:.2f}</td></tr>'
            )
        return "".join(rows)

    return (completion_rows,)


@app.cell(hide_code=True)
def _(completion_rows):
    _head = (
        "<tr><th>a</th><th>b</th><th>true mix</th><th>model's guess</th>"
        '<th class="num">distance</th><th class="num">floor</th></tr>'
    )
    _tables = []
    for _g, _es in [("v27", "named_holdout"), ("v216", "named_holdout"), ("v216", "open")]:
        _tables.append(
            mo.Html(
                figure_html(
                    f'<div class="report-table-scroll"><table class="report-table">{_head}'
                    f"{completion_rows(_g, _es)}</table></div>",
                    caption=f"`{_g}` · {_es.replace('_', ' ')}: the six widest misses (seed 0).",
                    class_="report-figure",
                )
            )
        )
    mo.vstack(_tables)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Discussion

    (to be written once results land)
    """)
    return


if __name__ == "__main__":
    app.run()
