"""The in-context grammar: token layout, the clean-context invariant, label positions, determinism."""

from __future__ import annotations

import numpy as np
import pytest

from sca.data import incontext as ic
from sca.data.named_colors import WordTokenizer
from sca.data.ops import DARKEN, LIGHTEN, MIX, NAMES, OPS
from sca.config import TokenizerConfig

RED, GREEN, GREY, WHITE, BLACK = (15, 0, 0), (0, 15, 0), (6, 6, 6), (15, 15, 15), (0, 0, 0)


# --- Token layout -----------------------------------------------------------------------------


def test_context_length_formula():
    for k in range(0, 5):
        assert ic.context_length(k) == 6 * k + 6
        assert ic.context_length(k, verify=True) == 6 * k + 8


def test_completion_context_words():
    ex = ic.Example(RED, GREEN, GREY, "true", "mix")
    ctx = ic.Context("mix", (ex,), WHITE, BLACK, GREY)
    assert ctx.words == [
        NAMES[RED], "?", NAMES[GREEN], "=", NAMES[GREY], ",",
        NAMES[WHITE], "?", NAMES[BLACK], "=", NAMES[GREY], "\n",
    ]  # fmt: skip
    assert len(ctx.words) == ctx.n_tokens == ic.context_length(1)
    assert ctx.words.count(ic.EXAMPLE_SEP) == 1  # closes the one example, not the query
    assert ctx.words[-1] == "\n"


def test_verification_context_words():
    ex = ic.Example(RED, GREEN, GREY, "true", "mix")
    verify = ic.Verification(GREY, True, "true", "mix")
    ctx = ic.Context("mix", (ex,), WHITE, BLACK, GREY, verify)
    assert ctx.words == [
        NAMES[RED], "?", NAMES[GREEN], "=", NAMES[GREY], ",",
        NAMES[WHITE], "?", NAMES[BLACK], "=", NAMES[GREY], ic.VERIFY_MARK, ic.TRUE_TOKEN, "\n",
    ]  # fmt: skip
    assert ctx.n_tokens == ic.context_length(1, verify=True)


def test_two_examples_no_separator_before_query():
    ex = ic.Example(RED, GREEN, GREY, "true", "mix")
    ctx = ic.Context("mix", (ex, ex), WHITE, BLACK, GREY)
    words = ctx.words
    # every example ends in a comma; only the query (the last unit) ends in a newline
    assert words.count(",") == 2
    assert words.count("\n") == 1
    assert words[-1] == "\n"


# --- The clean-context invariant (rho=cube_rate=0) --------------------------------------------


def _consistent_ops(op_table, examples):
    """Ops whose deterministic (exact) output agrees with every shown example — the discrete analogue of the
    posterior at rho=0. Not necessarily a singleton: two ops can coincide on a handful of examples, especially
    at small k ("where the op table allows", per the task's own phrasing)."""
    return {o.name for o in op_table if all(o(ex.lhs, ex.rhs) == ex.answer for ex in examples)}


@pytest.mark.parametrize("k", [1, 3, 4])
@pytest.mark.parametrize("seed", [0, 1, 2])
def test_clean_context_is_consistent_with_only_the_hidden_op(k, seed):
    """At rho=0 every example (and the query) is generated by the hidden op alone, under nearest rounding, so the
    hidden op is always exactly consistent with what's shown, and — as k grows — usually the only op that is
    (empirically ~63% at k=1, ~94% at k=3, ~98% at k=4 over table `OPS`; calibrated by direct simulation)."""
    rng = np.random.default_rng(seed)
    unique = 0
    n = 30
    for _ in range(n):
        hidden = OPS[int(rng.integers(len(OPS)))]
        ctx = ic.sample_context(OPS, hidden, k, rho=0.0, rng=rng)
        assert all(ex.source == "true" for ex in ctx.examples)
        assert all(ex.answer == hidden(ex.lhs, ex.rhs) for ex in ctx.examples)
        assert ctx.query_answer == hidden(ctx.query_lhs, ctx.query_rhs)

        consistent = _consistent_ops(OPS, ctx.examples)
        assert hidden.name in consistent  # the hidden op is never ruled out by its own examples
        unique += len(consistent) == 1

    # loose lower bounds well under the calibrated rates, just enough to catch a broken generator
    threshold = {1: 0.4, 3: 0.8, 4: 0.9}[k]
    assert unique / n >= threshold


def test_replacement_noise_only_at_rho_one():
    rng = np.random.default_rng(0)
    ctx = ic.sample_context(OPS, MIX, k=4, rho=1.0, rng=rng, cube_rate=0.0)
    assert all(ex.source == "noise" for ex in ctx.examples)
    assert all(ex.drawn_op != "mix" for ex in ctx.examples)  # "another op": never the hidden one
    assert ctx.query_answer == MIX(ctx.query_lhs, ctx.query_rhs)  # the query is always clean


def test_cube_noise_only_at_cube_rate_one():
    rng = np.random.default_rng(0)
    ctx = ic.sample_context(OPS, MIX, k=4, rho=0.0, rng=rng, cube_rate=1.0)
    assert all(ex.source == "cube" and ex.drawn_op is None for ex in ctx.examples)


def test_verification_verdict_matches_the_true_answer_whatever_branch_produced_it():
    """The verdict is a fact about the candidate, not a record of which branch drew it: a noise or cube draw
    that happens to equal the true answer is TRUE."""
    rng = np.random.default_rng(0)
    for _ in range(200):
        ctx = ic.sample_context(OPS, MIX, k=2, rho=0.5, rng=rng, cube_rate=0.2, verify_rate=1.0)
        assert ctx.verify is not None
        assert ctx.verify.verdict == (ctx.verify.candidate == ctx.query_answer)


def test_verify_rate_gates_whether_a_context_is_a_verification_line():
    rng = np.random.default_rng(0)
    never = [ic.sample_context(OPS, MIX, k=2, rho=0.2, rng=rng, verify_rate=0.0) for _ in range(20)]
    assert all(c.verify is None for c in never)
    always = [ic.sample_context(OPS, MIX, k=2, rho=0.2, rng=rng, verify_rate=1.0) for _ in range(20)]
    assert all(c.verify is not None for c in always)


# --- Determinism --------------------------------------------------------------------------------


def test_sample_corpus_is_deterministic_under_a_seed():
    a = ic.sample_corpus(50, seed=7, k=3, rho=0.3)
    b = ic.sample_corpus(50, seed=7, k=3, rho=0.3)
    assert a == b


def test_sample_corpus_seeds_differ():
    a = ic.sample_corpus(50, seed=7, k=3, rho=0.3)
    b = ic.sample_corpus(50, seed=8, k=3, rho=0.3)
    assert a != b


# --- Line/role arrays and the whole-line label -------------------------------------------------


def _tokenizer() -> WordTokenizer:
    return WordTokenizer(TokenizerConfig(vocabulary=sorted(ic.vocabulary())))


def test_line_role_arrays_recover_variable_length_contexts():
    tok = _tokenizer()
    corpus = ic.sample_corpus(6, seed=1, k=2, rho=0.3, verify_rate=0.5)
    tokens = ic.encode_corpus(corpus, tok.stoi)
    newline = tok.stoi["\n"]
    line, role = ic.line_role_arrays(tokens, newline)

    assert line[0] == 0 and role[0] == 0
    # every context's line id run is contiguous and as long as its own token count
    offset = 0
    for i, ctx in enumerate(corpus):
        n = ctx.n_tokens
        assert list(line[offset : offset + n]) == [i] * n
        assert list(role[offset : offset + n]) == list(range(n))
        offset += n
    assert offset == len(tokens)
    assert line.max() == len(corpus) - 1


def test_whole_line_mask_marks_every_token_of_a_labelled_context_and_no_other():
    tok = _tokenizer()
    corpus = ic.sample_corpus(30, seed=2, k=2, rho=0.3, op_table=(MIX, LIGHTEN, DARKEN))
    tokens = ic.encode_corpus(corpus, tok.stoi)
    newline = tok.stoi["\n"]
    line, _ = ic.line_role_arrays(tokens, newline)
    per_line_op = ic.op_ids(corpus, (MIX, LIGHTEN, DARKEN))

    rng = np.random.default_rng(0)
    mask = ic.whole_line_mask(line, per_line_op, anchored_op_id=0, label_rate=1.0, rng=rng)

    mix_lines = {i for i, ctx in enumerate(corpus) if ctx.op == "mix"}
    expected = np.isin(line, list(mix_lines))
    np.testing.assert_array_equal(mask, expected)
    # every position of a labelled context is pulled, not just a slot
    for i in mix_lines:
        positions = np.flatnonzero(line == i)
        assert mask[positions].all()


def test_whole_line_mask_label_rate_zero_labels_nothing():
    tok = _tokenizer()
    corpus = ic.sample_corpus(10, seed=3, k=2, rho=0.0, op_table=(MIX, LIGHTEN))
    tokens = ic.encode_corpus(corpus, tok.stoi)
    line, _ = ic.line_role_arrays(tokens, tok.stoi["\n"])
    per_line_op = ic.op_ids(corpus, (MIX, LIGHTEN))
    rng = np.random.default_rng(0)
    mask = ic.whole_line_mask(line, per_line_op, anchored_op_id=0, label_rate=0.0, rng=rng)
    assert not mask.any()


# --- Posterior, Bayes ceiling, target null ----------------------------------------------------


def test_posterior_is_a_distribution():
    rng = np.random.default_rng(0)
    ctx = ic.sample_context(OPS, MIX, k=3, rho=0.3, rng=rng)
    post = ic.posterior_over_ops(OPS, ctx.examples, rho=0.3)
    assert set(post) == {o.name for o in OPS}
    assert pytest.approx(sum(post.values()), abs=1e-9) == 1.0
    assert all(p >= 0 for p in post.values())


def test_posterior_prefixes_start_at_the_prior_and_end_at_the_full_posterior():
    rng = np.random.default_rng(0)
    ctx = ic.sample_context(OPS, MIX, k=3, rho=0.3, rng=rng)
    prefixes = ic.posterior_prefixes(OPS, ctx.examples, rho=0.3)
    assert len(prefixes) == 4
    assert prefixes[0] == {o.name: pytest.approx(1.0 / len(OPS)) for o in OPS}
    assert prefixes[-1] == ic.posterior_over_ops(OPS, ctx.examples, rho=0.3)


def test_bayes_ceiling_is_one_when_the_posterior_is_certain_and_the_query_is_on_grid():
    """The posterior always weighs likelihood under `answer_dist` — the stochastic-rounding model — even at
    rho=0 (`pivot.md#the-posterior-over-ops`), so the ceiling is below 1 in general even with no noise: an
    on-grid example still splits some likelihood to another op whose raw output also lands near the same
    color. Only once the posterior has fully settled on the hidden op (post == 1.0) AND the query itself is
    on-grid for it (so `answer_dist` there is a point mass) is the ceiling provably exactly 1."""
    from sca.data.ops import is_on_grid

    rng = np.random.default_rng(0)
    for _ in range(200):
        ctx = ic.sample_context(OPS, MIX, k=6, rho=0.0, rng=rng)
        post = ic.posterior_over_ops(OPS, ctx.examples, rho=0.0)
        if post["mix"] == 1.0 and is_on_grid(MIX, ctx.query_lhs, ctx.query_rhs):
            ceiling = ic.bayes_ceiling(OPS, ctx.examples, (ctx.query_lhs, ctx.query_rhs), rho=0.0)
            assert ceiling == pytest.approx(1.0)
            break
    else:
        pytest.skip("no draw in 200 tries hit a certain posterior with an on-grid query")


def test_bayes_ceiling_is_a_probability_at_least_as_good_as_the_hidden_op_alone():
    """Whatever the posterior spread, mixing in other ops can only help the best predictor: the ceiling is at
    least the probability mass the hidden op's own answer distribution puts on the true answer, discounted by
    its posterior share."""
    rng = np.random.default_rng(0)
    for _ in range(20):
        hidden = OPS[int(rng.integers(len(OPS)))]
        ctx = ic.sample_context(OPS, hidden, k=3, rho=0.0, rng=rng)
        post = ic.posterior_over_ops(OPS, ctx.examples, rho=0.0)
        query = (ctx.query_lhs, ctx.query_rhs)
        ceiling = ic.bayes_ceiling(OPS, ctx.examples, query, rho=0.0)
        floor = post[hidden.name] * ic.answer_dist(hidden, *query).get(ctx.query_answer, 0.0)
        assert 0.0 < ceiling <= 1.0 + 1e-9
        assert ceiling >= floor - 1e-9


def test_target_null_excludes_the_named_op_and_renormalizes():
    rng = np.random.default_rng(0)
    ctx = ic.sample_context(OPS, MIX, k=3, rho=0.3, rng=rng)
    null = ic.target_null(OPS, ctx.examples, (ctx.query_lhs, ctx.query_rhs), rho=0.3, exclude="mix")
    assert pytest.approx(sum(null.values()), abs=1e-9) == 1.0
    # excluding every op leaves nothing
    empty = ic.target_null((MIX,), ctx.examples, (ctx.query_lhs, ctx.query_rhs), rho=0.3, exclude="mix")
    assert empty == {}


def test_vocabulary_covers_every_word_a_corpus_uses():
    corpus = ic.sample_corpus(20, seed=4, k=3, rho=0.3, verify_rate=0.5)
    used = {w for ctx in corpus for w in ctx.words}
    assert used <= set(ic.vocabulary())
